# Generated by Django 4.0.6 on 2022-12-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='github_url',
            new_name='You_Tube',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='web_url',
            new_name='tik_tok',
        ),
    ]
